### PR TITLE
Fix compilation for ASIMD, fix #766

### LINKED ISSUE #766: NEON detection on aarch64 / TX1
Torch is failing to build on ARMv8 (Tegra X1) under Ubuntu 16.04 aarch64.
During configuration:
`-- Could not find hardware support for NEON on this machine.`

Then while building:

```
[ 46%] Building C object lib/TH/CMakeFiles/TH.dir/THVector.c.o
In file included from /tmp/luarocks_torch-scm-1-6670/torch7/lib/TH/THVector.c:2:0:
/tmp/luarocks_torch-scm-1-6670/torch7/lib/TH/generic/THVectorDispatch.c: In function ‘THByteVector_vectorDispatchInit’:
/tmp/luarocks_torch-scm-1-6670/torch7/lib/TH/generic/simd/simd.h:60:3: error: impossible constraint in ‘asm’
   asm volatile ( "cpuid\n\t"
   ^
/tmp/luarocks_torch-scm-1-6670/torch7/lib/TH/generic/simd/simd.h:60:3: error: impossible constraint in ‘asm’
   asm volatile ( "cpuid\n\t"
   ^
lib/TH/CMakeFiles/TH.dir/build.make:350: recipe for target 'lib/TH/CMakeFiles/TH.dir/THVector.c.o' failed
```

It looks like [FindARM.cmake](https://github.com/torch/torch7/blob/eb8d7f2752f2b714135b862d148600c60329ac26/lib/TH/cmake/FindARM.cmake) searches /proc/cpuinfo for 'neon'.  However, ARMv8 output is the following:

```
Features        : fp asimd aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd07
CPU revision    : 1
Hardware        : jetson_tx1
```

It appears like other [[1](https://bugs.chromium.org/p/libyuv/issues/detail?id=361)][[2](http://stackoverflow.com/a/14762516)] ARMv8 platforms may also list `asimd` in leui of `neon` in their `/proc/cpuinfo`.

### PR DESCRIPTION
**Pull request by Atcold**
On ARMv8, neon is inherit and instead listed as 'asimd' in /proc/cpuinfo
Replace assembly with C

Original authors:
 - @dusty-nv
    FindARM-patch.txt
    CMakeLists-patch.txt
 - @rtarquini
    NEON.c

### CODE REVIEW

**Comment by soumith** [comment]
thank you!

**Comment by Atcold** [comment]
@soumith, *Travis* says it fails with `clang` and and `LUA52`... Is that OK?

**Comment by soumith** [comment]
yes, i fixed the failure (it was a flaky test which i bumped up the tolerance)
