### ISSUE TITLE
NEON detection on aarch64 / TX1

### ISSUE THREAD

**Issue by dusty-nv** [torch/torch7#766]
Torch is failing to build on ARMv8 (Tegra X1) under Ubuntu 16.04 aarch64.
During configuration:
`-- Could not find hardware support for NEON on this machine.`

Then while building:

```
[ 46%] Building C object lib/TH/CMakeFiles/TH.dir/THVector.c.o
In file included from /tmp/luarocks_torch-scm-1-6670/torch7/lib/TH/THVector.c:2:0:
/tmp/luarocks_torch-scm-1-6670/torch7/lib/TH/generic/THVectorDispatch.c: In function ‘THByteVector_vectorDispatchInit’:
/tmp/luarocks_torch-scm-1-6670/torch7/lib/TH/generic/simd/simd.h:60:3: error: impossible constraint in ‘asm’
   asm volatile ( "cpuid\n\t"
   ^
/tmp/luarocks_torch-scm-1-6670/torch7/lib/TH/generic/simd/simd.h:60:3: error: impossible constraint in ‘asm’
   asm volatile ( "cpuid\n\t"
   ^
lib/TH/CMakeFiles/TH.dir/build.make:350: recipe for target 'lib/TH/CMakeFiles/TH.dir/THVector.c.o' failed
```

It looks like [FindARM.cmake](https://github.com/torch/torch7/blob/eb8d7f2752f2b714135b862d148600c60329ac26/lib/TH/cmake/FindARM.cmake) searches /proc/cpuinfo for 'neon'.  However, ARMv8 output is the following:

```
Features        : fp asimd aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd07
CPU revision    : 1
Hardware        : jetson_tx1
```

It appears like other [[1](https://bugs.chromium.org/p/libyuv/issues/detail?id=361)][[2](http://stackoverflow.com/a/14762516)] ARMv8 platforms may also list `asimd` in leui of `neon` in their `/proc/cpuinfo`.

**Comment by dusty-nv** [comment]
Note:   after manually patching FindARM.cmake to set `NEON_TRUE` and omit -mfpu=neon (as mentioned [here](http://stackoverflow.com/a/29891469)), I encounter the same errors from issue [763](https://github.com/torch/torch7/issues/763).

**Comment by soumith** [comment]
@dusty-nv #763 is now fixed in master

**Comment by soumith** [comment]
if you can send a patch to FindARM.cmake to work for armv8, it would be much appreciated.

**Comment by dusty-nv** [comment]
Thanks Soumith.    Try these patches below for FindARM.cmake and lib/TH/CMakeLists are a bit crude, because I still define __NEON__ directive on ARMv8 so it compiles the rest of the code normally.

[FindARM-patch.txt](https://github.com/torch/torch7/files/505088/FindARM-patch.txt)
[CMakeLists-patch.txt](https://github.com/torch/torch7/files/505089/CMakeLists-patch.txt)

**Comment by rtarquini** [comment]
Did a pull today 10/14/2016. There is still are problems on the X1 build. 

(1) /pkg/torch/lib/TH/CMakeLists.txt
     FIND_PACKAGE(ARM) - does not result in NEON_FOUND. 
             i.e the default case does not set -D__NEON___
     - I'm only building for the X1/64 bit, so I just always define this
(2)  /pkg/torch/lib/TH/vector/NEON.c
     Assembly instructions are invalid for ARM64.  
     - reverted to generic 'C' functions from previous ThVector.c
        I can post this file if interested.
(3)  Build processes are being killed. (Low memory?)

Not sure how to resolve #3? Ideas? 

-Rich

**Comment by rtarquini** [comment]
Replacing the ../luarocks make with ../luarocks install resolves the memory issues with the problematic rocks such as cutorch.  The rock specs in the distribution need to be refreshed.

**Comment by soumith** [comment]
@rtarquini fixed via https://github.com/torch/cutorch/commit/ac40c058125cae4abb459ebad3d07e10ce858e8d

**Comment by dusty-nv** [comment]
@rtarquini can you post your ThVector.c?     I'm getting invalid assembly instructions too after forcing NEON_FOUND with latest pull.

**Comment by rtarquini** [comment]
ThVector.c includes ./vector/NEON.c. That is the file with the mods. 

[NEON.c.txt](https://github.com/torch/torch7/files/536328/NEON.c.txt)

**Comment by dusty-nv** [comment]
Thanks @rtarquini, I got master building on aarch64 again with the file.   On TX1 it still requires swap and enough disk space in /tmp for me with jopts=1, when cutorch begins compiling large templates in THCTensorMathPointwise.cu.

**Comment by Atcold** [comment]
Installation on TX1 still breaks (fixed with the two patches and the new `NEON.c`) and it's taking ages (it's been 4 hours that I've been trying to install `cutorch`). Installing an older version does take a minute or two.
For the swap, I just plugged in a SSD as "additional RAM".
This is a nightmare, especially with deadlines coming up too soon.

**Comment by hit1001** [comment]
While trying out on aarch64 platform i am still getting these errors.

**Comment by Atcold** [comment]
@hit1001, you need to `cd` into `torch7` repo, and `patch <`[`CMakeLists-patch.txt`](https://github.com/torch/torch7/files/505089/CMakeLists-patch.txt) replace `lib/TH/vector/NEON.c` with [`NEON.c`](https://github.com/torch/torch7/files/536328/NEON.c.txt), `cd` into `torch7/lib/TH/cmake/` and run `patch < `[`FindARM-patch.txt`](https://github.com/torch/torch7/files/505088/FindARM-patch.txt).
You will also need to create a swap file. See [this](https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04) for a nice tutorial about the *how*.

**Comment by soumith** [comment]
@Atcold if you hav ea solution to this, can you please send in a PR? I dont have an AArch64 to test out, and hence was unable to fix it myself.

**Comment by Atcold** [comment]
Oh, OK. I didn't know @soumith.
The problem is that it takes one whole night to install `cutorch`. I'm not sure this is a *feasible* solution. Moreover, one need an external SSD drive (swapping on USB is a suicide).

**Comment by hit1001** [comment]
@Atcold, i am trying to install torch/distro. so the files you mentioned lies in /pkg/torch/TH ..
The thing are torch7 and cutorch additional packages apart from those in directory pkg? after patching it still doesnt build up for me. 
If yes, how do i install them? @dusty-nv :_ Do i follow the CMakePrebuild.sh for torch7?

**Comment by Atcold** [comment]
@hit1001, this is my `~/torch/pkg/torch` repo on my TX1.
![status](https://cloud.githubusercontent.com/assets/2119355/20320286/5e993870-ab3f-11e6-8e44-e1a2d331f911.png)
You can simply apply this [`patch.txt`](https://github.com/torch/torch7/files/592917/patch.txt). For me it work *as long as* you have *enough swap* (see [this](https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04) article about how to create some swap file).

**Comment by soumith** [comment]
@Atcold i would appreciate it if you send a PR so that folks dont need to manually apply this patch. I cant create the PR, as I cannot test the ARM64 side.
Thanks.

**Comment by Atcold** [comment]
@soumith, I am not the author of the code. I've just used @dusty-nv and @rtarquini work. Shall I send a PR citing the authors? I am also not aware if this breaks anything else.

**Comment by soumith** [comment]
yes, please do. we will catch other issues in contbuild

**Comment by Atcold** [comment]
Here you go #839.
